# Generated by Django 4.0.3 on 2023-11-08 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('numero_telefonico', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('ENVIADO', 'Enviado')], max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('DÉBITO/CRÉDITO', 'Débito/Crédito')], max_length=255)),
                ('total', models.IntegerField()),
                ('productos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
        ),
    ]
