# Generated by Django 4.0.3 on 2023-11-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CANCELADO', 'Cancelado'), ('CERRADO', 'Cerrado')], max_length=255),
        ),
    ]
