# Generated by Django 4.0.3 on 2023-11-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
